author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/getEncryption'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '202112082114'
      #password 密码
      password: 'wyk197615'
      #address 地址，定位信息
      address: '福建省福州市连江县潘渡镇福建商学院四号楼'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '515939315@qq.com'
      #school 学校全称
      schoolName: 福建商学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.470747
      #lat 纬度
      lat: 26.250554
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      isOffset: true      
      # 表单信息
      forms:
        - form:
            title: 你是否有发热（≥37.3℃）、乏力、干咳、咽痛、急性腹泻等传染病相关症状
            value: 否
        - form:
            title: 你今天晚上18：00－22：00间的体温
            value: 其它
            other: 36.5
        - form:
            title: 本人承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处
            value: 是
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '202112082118'
      #password 密码
      password: 'q578784505'
      #address 地址，定位信息
      address: '福建省福州市连江县潘渡镇福建商学院四号楼'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '578784505@qq.com'
      #school 学校全称
      schoolName: 福建商学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.470747
      #lat 纬度
      lat: 26.250554
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      isOffset: true      
      # 表单信息
      forms:
        - form:
            title: 你是否有发热（≥37.3℃）、乏力、干咳、咽痛、急性腹泻等传染病相关症状
            value: 否
        - form:
            title: 你今天晚上18：00－22：00间的体温
            value: 其它
            other: 36.5
        - form:
            title: 本人承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处
            value: 是
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '202112082116'
      #password 密码
      password: 'z5201314.'
      #address 地址，定位信息
      address: '福建省福州市连江县潘渡镇福建商学院四号楼'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '2499895341@qq.com'
      #school 学校全称
      schoolName: 福建商学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.470747
      #lat 纬度
      lat: 26.250554
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      isOffset: true      
      # 表单信息
      forms:
        - form:
            title: 你是否有发热（≥37.3℃）、乏力、干咳、咽痛、急性腹泻等传染病相关症状
            value: 否
        - form:
            title: 你今天晚上18：00－22：00间的体温
            value: 其它
            other: 36.5
        - form:
            title: 本人承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处
            value: 是
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '202112082104'
      #password 密码
      password: 'zxcvbnm0'
      #address 地址，定位信息
      address: '福建省福州市连江县潘渡镇福建商学院四号楼'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '1678916796@qq.com'
      #school 学校全称
      schoolName: 福建商学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.470747
      #lat 纬度
      lat: 26.250554
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      isOffset: true      
      # 表单信息
      forms:
        - form:
            title: 你是否有发热（≥37.3℃）、乏力、干咳、咽痛、急性腹泻等传染病相关症状
            value: 否
        - form:
            title: 你今天晚上18：00－22：00间的体温
            value: 其它
            other: 36.5
        - form:
            title: 本人承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处
            value: 是          
